---

swarm:
  hosts:
    node001:
      ansible_host: MY1
      ansible_ssh_user: ansible
    node002:
      ansible_host: MY2
      ansible_ssh_user: ansible
    node003:
      ansible_host: MY3
      ansible_ssh_user: ansible
    node004:
      ansible_host: MY4
      ansible_ssh_user: ansible

managers:
  hosts:
    # Only include the manager nodes
    node001:
      ansible_host: MY1
      ansible_ssh_user: ansible
    node002:
      ansible_host: MY2
      ansible_ssh_user: ansible

workers:
  hosts:
    # Only include the manager nodes
    node003:
      ansible_host: MY3
      ansible_ssh_user: ansible
    node004:
      ansible_host: MY4
      ansible_ssh_user: ansible
